name: Deployment
on:
  push:
    branches:
      - main
      - dev
      - master
env:
  PORT: 8080
jobs:
  test:  
    runs-on: ubuntu-latest
    environment: testing
    env:
      MONGODB_CLUSTER_ADDRESS:  ac-h7iydk9-shard-00-01.bbk6yqk.mongodb.net
      MONGODB_DB_NAME: ghamongodb
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT
      - name: Run tests
        run: npm test
      - name: Output information
        run: |
          echo "MONGODB_CLUSTER_ADDRESS: ${{env.MONGODB_CLUSTER_ADDRESS}}"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |        
          echo "PORT: $PORT"